server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoletadb
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  cloud:
    config:
      enabled: false

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
